apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 10.0.2.21
  ports:
  - port: 54881
- addresses:
  - ip: 10.0.2.22
  ports:
  - port: 54881
- addresses:
  - ip: 10.0.2.23
  ports:
  - port: 54881
